// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Naxam.I18n.Demo {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalTexts_vi {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalTexts_vi() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Naxam.I18n.Demo.LocalTexts.vi", typeof(LocalTexts_vi).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string List_Title {
            get {
                return ResourceManager.GetString("List.Title", resourceCulture);
            }
        }
        
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        internal static string TimeAgo_NA {
            get {
                return ResourceManager.GetString("TimeAgo.NA", resourceCulture);
            }
        }
        
        internal static string TimeAgo_LessThan1Minute {
            get {
                return ResourceManager.GetString("TimeAgo.LessThan1Minute", resourceCulture);
            }
        }
        
        internal static string TimeAgo_LessThan5Minutes {
            get {
                return ResourceManager.GetString("TimeAgo.LessThan5Minutes", resourceCulture);
            }
        }
        
        internal static string TimeAgo_LessThan1Hour {
            get {
                return ResourceManager.GetString("TimeAgo.LessThan1Hour", resourceCulture);
            }
        }
        
        internal static string TimeAgo_LessThan1Day {
            get {
                return ResourceManager.GetString("TimeAgo.LessThan1Day", resourceCulture);
            }
        }
        
        internal static string TimeAgo_Yesterday {
            get {
                return ResourceManager.GetString("TimeAgo.Yesterday", resourceCulture);
            }
        }
        
        internal static string TimeAgo_LessThan1Week {
            get {
                return ResourceManager.GetString("TimeAgo.LessThan1Week", resourceCulture);
            }
        }
        
        internal static string TimeAgo_Past {
            get {
                return ResourceManager.GetString("TimeAgo.Past", resourceCulture);
            }
        }
    }
}
